# crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.example.com  # must be plural.group
spec:
  group: example.com         # your API group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                color:
                  type: string
      subresources:
        status: {}
  scope: Namespaced           # or Cluster
  names:
    plural: widgets
    singular: widget
    kind: Widget
    shortNames:
    - wd
