apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiI5MTYwNzgyMTJAcXEuY29tIiwicGFzc3dvcmQiOiJmam9pYWpmZCFFYWY5YXNkZiIsImF1dGgiOiJPVEUyTURjNE1qRXlRSEZ4TG1OdmJUcG1hbTlwWVdwbVpDRkZZV1k1WVhOa1pnPT0ifX19
kind: Secret
metadata:
  name: my-imagepullsecret
  namespace: default
type: kubernetes.io/dockerconfigjson
