apiVersion: v1
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "username",
          "password": "password",
          "auth": ""
        }
      }
    }
kind: Secret
metadata:
  name: my-imagepullsecret
  namespace: default
type: kubernetes.io/dockerconfigjson
