apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
         # Use Secret as environment variables
      env:
        - name: test-username
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: test-password
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

        # Mount the Secret as files
      volumeMounts:
        - name: secret-files
          mountPath: /etc/secret-config

  volumes:
  - name: secret-files
    secret:
      secretName: my-secret
