apiVersion: v1
kind: Pod
metadata:
  name: alpine-config-test
spec:
  containers:
    - name: alpine-container
      image: alpine:latest
      # We added 'env' to the command so it prints your variables to the log
      command: ["/bin/sh", "-c", "env && sleep 3600"]
      envFrom:
        - configMapRef:
            name: my-configmap
