apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: ubuntu:latest
    command: ["sh", "-c"]
    args:
    - |
      echo "Command 1"
      echo "Command 2"
      echo "Command 3"
    tty: true
