apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: Pod
metadata:
  name: my-local-pod
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["sh", "-c", "echo Hello Kubernetes! > /data/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: my-local-storage
  volumes:
  - name: my-local-storage
    persistentVolumeClaim:
      claimName: my-pvc
