services:
  web:
    image: nginx
    container_name: web
    networks:
      - mynet

  app:
    image: alpine
    container_name: app
    command: sh -c "sleep 3600"   # keep container running
    networks:
      - mynet

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
