apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp-2
  template:
    metadata:
      labels:
        app: helloapp-2
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
        name: hello-app
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloapp-2
