apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp1
spec:
  selector:
    matchLabels:
      app: helloapp1
  template:
    metadata:
      labels:
        app: helloapp1
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp2
spec:
  selector:
    matchLabels:
      app: helloapp2
  template:
    metadata:
      labels:
        app: helloapp2
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
