apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-readonly
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do echo hello; sleep 5; done"]
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /run
        - name: devshm
          mountPath: /dev/shm
  volumes:
    - name: tmp
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: devshm
      emptyDir: {}
