apiVersion: v1
kind: Pod
metadata:
  name: app-pod-1
  labels:
    app: myapp
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-2
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx
