apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    app: myweb
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        # image: nginx
        image: luksa/kubia
        ports:
        - containerPort: 8080
---


# kubectl expose rc my-rc --name my-rc-svc --type=NodePort
