apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/zchun/Downloads/35740918/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
