apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
spec:
  # persistentVolumeClaimRetentionPolicy:
  #   whenDeleted: Retain
  #   whenScaled: Retain
  # persistentVolumeClaimRetentionPolicy:
  #    whenDeleted: Delete
  #    whenScaled: Delete
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 3
  #podManagementPolicy: OrderedReady
  #podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
# Create a Client for MySQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - image: ubuntu
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "apt update && apt install -y mysql-client"]
        name: mysql-client
        stdin: true
        tty: true
