apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: my-user

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-09-13T14:00:43Z"
  name: my-sa
  namespace: default

---
