---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-demo
  
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1
subjects:
- kind: ServiceAccount
  name: sa-demo
  namespace: default


---
# kubectl create serviceaccount sa-demo 
# kubectl create role role1 --verb=list --resource=pods
# kubectl create rolebinding rb1 --role=role1  --serviceaccount=default:sa-demo


