---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-demo
  
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

---
