apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-readonly
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "--"]
      args:
        - |
          echo "Root filesystem is read-only, but /tmp is writable.";
          while true; do
            date >>  /tmp/demo.txt;
            cat /tmp/demo.txt;
            sleep 5;
          done
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: opt
          mountPath: /opt
  volumes:
    - name: tmp
      emptyDir: {}
    - name: opt
      emptyDir: {}
