apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - 24h
    image: arm64v8/alpine
    name: pod-with-sa
  serviceAccountName: my-sa
