apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: clusterip-web
  ports:
    - port: 80          # Internal ClusterIP port
      targetPort: 80    # Port inside the Pod
