apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deploy
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["sh", "-c", "while true; do sleep 3600; done"]

