apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/dnsutils-arm:1.2
    name: dnsutils
    tty: true
    stdin: true
