apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: alpine 
        name: alpine
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "apk add --update bind-tools; apk add --update curl"]
        stdin: true
        tty: true
