apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do { echo -e \"HTTP/1.1 200 OK\n\nHello from $(hostname)\"; } | nc -l -p 8080; done"]
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-svc
spec:
  selector:
    app: busybox
  ports:
  - port: 8080       # Service port
    targetPort: 8080 # Pod port
