apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp1
  template:
    metadata:
      labels:
        app: helloapp1
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m


---
apiVersion: v1
kind: Service
metadata:
  name: helloapp1-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloapp1
  type: ClusterIP