apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-privileged
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y netcat wget openjdk-17-jdk vim && sleep infinity
    securityContext:
      privileged: true
