apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-privileged
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
