apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
      env:
        - name: test1
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
