apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        livenessProbe:
          httpGet:
            path: /usr/share/nginx/html/index2.html
            port: 8080



  # Warning  Unhealthy  114s (x9 over 3m14s)   kubelet            Liveness probe failed: Get "http://10.1.0.97:8080/usr/share/nginx/html/index2.html": dial tcp 10.1.0.97:8080: connect: connection refused
  # Normal   Killing    114s (x3 over 2m54s)   kubelet            Container nginx failed liveness probe, will be restarted


