apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubia-demo
  name: kubia-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-demo
  template:
    metadata:
      labels:
        app: kubia-demo
    spec:
      containers:
      - image: luksa/kubia:latest
        name: kubia


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubia-demo
  name: kubia-demo-svc-clusterip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia-demo

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubia-demo
  name: kubia-demo-svc-nodeport
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubia-demo
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-headless
spec:
  clusterIP: None  # This makes the service headless
  selector:
    app: kubia-demo  # Select pods with label 'app: my-app'
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
