apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: ubuntu
        stdin: true
        tty: true

---
