apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
      # - image: gcr.io/google-samples/hello-app:2.0
        name: hello-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
  name: hello-server-svc-np
spec:
  ports:
  - nodePort: 31248
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
  name: hello-server-svc-cip
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-server
