apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-kubia
  name: my-kubia
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kubia
  template:
    metadata:
      labels:
        app: my-kubia
    spec:
      containers:
      - image: luksa/kubia:latest
        name: kubia
