# Create a Client for MySQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - image: ubuntu
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "apt update && apt install -y mysql-client netcat"]
        name: mysql-client
        stdin: true
        tty: true
