apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    # 'command' overrides the entrypoint, 'args' provides the script
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do 
          sleep 30; 
        done
