apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /etc/secret-volume/username"]
      volumeMounts:
        - name: secret-vol
          mountPath: "/etc/secret-volume"
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret
