apiVersion: v1
kind: Pod
metadata:
  name: secret-env-demo
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: DEMO_USER
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: username
    - name: DEMO_PASS
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: password

