apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    app: myweb
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        # image: nginx
        image: luksa/kubia
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-svc
spec:
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myweb
  type: NodePort
