apiVersion: v1
kind: Pod
metadata:
  name: baeldung-test-pod
spec:
  containers:
  - name: baeldung-test-container
    image: ubuntu:latest
    command: ["/bin/bash", "-c"]
    args: ["/tmp/myscript.sh"]
    volumeMounts:
    - name: baeldung-script-volume
      mountPath: /tmp/
      readOnly: true
  volumes:
  - name: baeldung-script-volume
    configMap:
      defaultMode: 0700
      name: myconfigmap
---
