---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-xxx
data:
  student_age: "10"
  student_name: xiaoming


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-demo
  template:
    metadata:
      labels:
        app: env-demo
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        name: alpine
        stdin: true
        tty: true
        env:
          - name: ENV1
            valueFrom:
              configMapKeyRef:
                name: configmap-xxx
                key: student_name
          - name: ENV2
            valueFrom:
              configMapKeyRef:
                name: configmap-xxx
                key: student_age



---

