apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
spec:
  secretName: root-secret
  dnsNames:
  - "*.default.svc.cluster.local"
  issuerRef:
    name: selfsigned-issuer
