apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.myapp.example.com
spec:
  group: myapp.example.com
  scope: Namespaced
  names:
    plural: myapps
    singular: myapp
    kind: MyApp
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}  # Allows Kopf to patch status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                replicas:
                  type: integer
                image:
                  type: string
            status:
              type: object
              properties:
                create_myapp:
                  type: object
                  properties:
                    message:
                      type: string
