apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-daemon
  template:
    metadata:
      labels:
        app: my-daemon
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["sh", "-c", "while true; do date; sleep 1; done"]
