apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
spec:
  secretName: my-tls-secret
  dnsNames:
    - localhost
    - example.com
    - www.example.com
    - "*.default.svc.cluster.local"
  issuerRef:
    name: my-selfsigned-issuer
