apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
      env:
        - name: test-username
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: test-password
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
