apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  student_age: "10"
  student_name: xiaoming

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-configmap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-demo
  template:
    metadata:
      labels:
        app: env-demo
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        name: alpine
        stdin: true
        tty: true
        env:
          - name: env1
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: student_name
          - name: env2
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: student_age



---

