apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  test: |
    hello world
---
apiVersion: v1
kind: Pod
metadata:
  name: my-alpine
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine
    name: my-alpine
    volumeMounts:
    - name: my-volume
      mountPath: /tmp
  volumes:
  - name: my-volume
    configMap:
      name: my-configmap
