apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: luksa/kubia:latest
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-rs-svc
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: my-app
  type: NodePort
