apiVersion: v1
kind: Service
metadata:
  name: my-rs-svc
  namespace: default
spec:
  # ports:
  # - nodePort: 31860
  #   port: 8080
  #   protocol: TCP
  #   targetPort: 8080
  selector:
    app: my-app
  type: NodePort
